# bayescl/hp/imagenetr/lora 88eba84
# 65.53% Acc. 11.31% ECE
# Selected best run based on highest accuracy from 15 trials
include:
- ../base.yaml
- ../base/dataset/imagenetr.yaml
- ../base/method/02_lora.yaml
lr: 0.00064
