# bayescl/hp/core50/der 9867fb2
# 56.82% Acc. 19.73% ECE
# Score 68.55% (ACC+(1-ECE))/2
# Selected best run based on highest score 9 trials
include:
- ../base.yaml
- ../base/dataset/core50.yaml
- ../base/method/06_der.yaml
lr: 0.00023
strategy:
  alpha: 0.26
  beta: 0.62
