# bayescl/hp/core50/ball 9867fb2
# 54.63% Acc. 8.04% ECE
# Score 73.30% (ACC+(1-ECE))/2
# Selected best run based on highest score 10 trials
include:
- ../base.yaml
- ../base/dataset/core50.yaml
- ../base/method/ball.yaml
lr: 0.00052
strategy:
  beta: 1.5
