include: [configs/core50/base.yaml]
label: blob

peft:
  type: BLoB
  beta: 1.0
  config:
    r: 4
    blob_A:
      prior_mu: 0.0
      prior_sigma: 1.0

      init_mu_mean: 0.0
      init_sigma_mean: 0.05

      init_mu_std: 1e-3
      init_rho_std: 1e-3

    blob_B:
      prior_mu: 0.0
      prior_sigma: 0.1

      # Initialization is close to zero to give BLoB a warm start
      init_mu_mean: 0.0
      init_sigma_mean: 1e-5

      init_mu_std: 1e-5
      init_rho_std: 0
