# bayescl/hp/core50/rwalk 9867fb2
# 46.36% Acc. 40.79% ECE
# Score 52.79% (ACC+(1-ECE))/2
# Selected best run based on highest score 10 trials
include:
- ../base.yaml
- ../base/dataset/core50.yaml
- ../base/method/rwalk.yaml
lr: 0.002
rwalk:
  ewc_alpha: 0.76
  ewc_lambda: 0.77
