label: ball

peft:
  type: BALL
  beta: 1.0
  first_task_beta: 0.01

  vbll: True
  bayes_eval_samples: 5
  config:
    r: 10
    vbnn:
      prior_loc: 0.0
      prior_std: 0.5
      init_sigma_loc: 0.1
      init_sigma_std: 0.01
      deterministic_eval: false

hpsearch:
  params:
    "peft.beta": {type: float, low: 0.01, high: 5, log: True}
    "peft.first_task_beta": {type: float, low: 0.01, high: 2, log: True}
