label: blob


peft:
  type: BLoB
  beta: 0.0
  vbll: False
  bayes_eval_samples: 5
  config:
    r: 10
    vbnn:
      prior_mu: 0.0
      prior_sigma: 0.5
      init_sigma: 0.1
      init_sigma_scale: 0.01
      deterministic_eval: false
  save: true

hpsearch:
  params:
    "peft.beta": {type: float, low: 0.01, high: 2, log: True}
