label:
  method: ball

# BALL uses local CE but it is implemented internally so we turn this off here
use_local_ce: False

peft:
  type: BALL
  beta: 1.0

  vbll: False
  train_samples: 1
  test_samples: 5

  config:
    r: 10

hpsearch:
  params:
    "peft.beta": {type: float, low: 1.0, high: 100.0, log: True}
