label:
  method: der

peft:
  type: LoRA
  r: 10

strategy:
  type: DER
  mem_size: 2000
  alpha: 0.1
  beta: 0.5

use_local_ce: false

hpsearch:
  params:
    "strategy.alpha": {type: float, low: 0.0, high: 1.0, log: False}
    "strategy.beta": {type: float, low: 0.0, high: 1.0, log: False}
