label:
  method: ewc

peft:
  type: LoRA
  r: 10

ewc:
  ewc_lambda: 1.0
  decay_factor: 0.9

hpsearch:
  params:
    "ewc.ewc_lambda": {type: float, low: 0.0, high: 10.0, log: False}
    "ewc.decay_factor": {type: float, low: 0.8, high: 1.0, log: False}
