label:
  method: tball

# BALL uses local CE but it is implemented internally so we turn this off here
use_local_ce: False

peft:
  type: TBALL
  rank: 10
  init_sd: 0.5
  prior_weight_sd: 1.0

strategy:
  type: VCL
  beta: 1.0
  train_samples: 1
  test_samples: 5

hpsearch:
  n_trials: 15
  params:
    "strategy.beta": {type: float, low: 1e-5, high: 1.0, log: True}
    "peft.bnn": {type: categorical, choices: ["FCG", "FFG"]}
    "peft.alpha": {type: float, low: 0.5, high: 1.5, log: False}
    "peft.bias": {type: categorical, choices: [true, false]}
