# bayescl/hp/domainnet/ball 88eba84
# 76.95% Acc. 1.84% ECE
# Selected best run based on highest accuracy from 15 trials
include:
- ../base.yaml
- ../base/dataset/domainnet.yaml
- ../base/method/03_ball.yaml
lr: 0.00055
peft:
  beta: 0.69
