# Tune BLoB
include: [../base.yaml, 00_base.yaml]
label: blob

# From hyper-parameter search bayescl/SplitCIFAR100/blob/adb502b (id=5162) n=10
lr: 0.0033118018204161864

peft:
  type: BLoB
  # From hyper-parameter search bayescl/SplitCIFAR100/blob/adb502b (id=5162) n=10
  beta: 0.9870219406091099
  config:
    r: 10
    blob_B:
      prior_mu: 0.0
      prior_sigma: 1.0

      init_mu_mean: 0.0
      init_sigma_mean: 0.1

      init_mu_std: 1e-3
      init_rho_std: 1e-3

      deterministic_eval: True

    blob_A:
      prior_mu: 0.0
      prior_sigma: 1.0

      # Initialization is close to zero to give BLoB a warm start
      init_mu_mean: 0.0
      init_sigma_mean: 0.001

      init_mu_std: 0.0
      init_rho_std: 1e-3

      deterministic_eval: True


hpsearch:
  params:
    "peft.beta": {type: float, low: 0.01, high: 10, log: False}
