# bayescl/hp/domainnet/l2p 16a14e7
# 70.12% Acc. 4.17% ECE
# Selected best run based on highest accuracy from 15 trials
include:
- ../base.yaml
- ../base/dataset/domainnet.yaml
- ../base/method/09_l2p.yaml
lr: 0.00096
peft:
  prompt_length: 6
  prompts_per_task: 5
  pull_constraint_coeff: 1.9
  top_k: 4
