# Fit a linear layer to a pretrained model
include: [../base.yaml, 00_base.yaml]
label: linear

# From hyper-parameter search bayescl/SplitCIFAR100/linear/37a54b2 (id=5134) n=10
lr: 0.0001

model:
  freeze_backbone: True
