# Tune BLoB
include: [../base.yaml, 00_base.yaml]
label: blob

# From hyper-parameter search bayescl/SplitCIFAR100/blob/adb502b (id=5162) n=10
lr: 0.002
first_exp_epochs: 40
epochs: 20

peft:
  type: BLoB
  # From hyper-parameter search bayescl/SplitCIFAR100/blob/adb502b (id=5162) n=10
  beta: 0.07
  vbll: False
  # bayes_eval_samples: 10
  config:
    r: 10
    vbnn:
      prior_mu: 0.0
      prior_sigma: 0.5
      init_sigma: 0.1
      init_sigma_scale: 0.01
      deterministic_eval: true
hpsearch:
  params:
    "peft.beta": {type: float, low: 0.01, high: 2, log: True}
    # "peft.vbll": {type: categorical, choices: [True, False]}
    # "outlier_exposure.strength": {type: float, low: 0.1, high: 2, log: True}

  n_trials: 50
  optimizer: "TPE"
