# Tune BLoB
include: [../base.yaml, 00_base.yaml]
label: blob

# From hyper-parameter search bayescl/SplitCIFAR100/blob/adb502b (id=5162) n=10
lr: 0.0033118018204161864

peft:
  type: BLoB
  # From hyper-parameter search bayescl/SplitCIFAR100/blob/adb502b (id=5162) n=10
  beta: 0.9870219406091099
  config:
    r: 10
    blob_A:
      deterministic_eval: true
      init_mu_mean: 0.0
      init_mu_std: 0.0
      init_rho_std: 0.001
      init_sigma_mean: 0.001
      prior_mu: 0.0
      prior_sigma: 1.0
    blob_B:
      deterministic_eval: true
      init_mu_mean: 0.0
      init_mu_std: 0.001
      init_rho_std: 0.001
      init_sigma_mean: 0.05
      prior_mu: 0.0
      prior_sigma: 1.0
hpsearch:
  params:
    "peft.beta": {type: float, low: 0.01, high: 50, log: False}
