# bayescl/hp/cifar100/tball e0522f4
# 60.35% Acc. 2.71% ECE
# Score 78.82% (ACC+(1-ECE))/2
# Selected best run based on highest score 10 trials
include:
- ../base.yaml
- ../base/dataset/cifar100.yaml
- ../base/method/11_tball.yaml
lr: 0.0025
peft:
  bnn: FFG
strategy:
  beta: 0.62
