# bayescl/hp/cifar100/lora 9867fb2
# 37.93% Acc. 8.44% ECE
# Score 64.74% (ACC+(1-ECE))/2
# Selected best run based on highest score 10 trials
include:
- ../base.yaml
- ../base/dataset/cifar100.yaml
- ../base/method/lora.yaml
lr: 0.00011
