# bayescl/hp/cifar100/rwalk 9867fb2
# 64.46% Acc. 11.97% ECE
# Score 76.24% (ACC+(1-ECE))/2
# Selected best run based on highest score 10 trials
include:
- ../base.yaml
- ../base/dataset/cifar100.yaml
- ../base/method/rwalk.yaml
lr: 0.0036
rwalk:
  ewc_alpha: 0.27
  ewc_lambda: 0.07
